package agostiniCamposampiero.deserto.grafica;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author giaco
 */
public class Grafica extends JFrame {

    /**
     * Creates new form Grafica
     */
    public Grafica() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(20,20,(int)(screenSize.width/10*7.5), screenSize.height/10*6);
        setVisible(true);
        messaggi = new JFrame();
        pannelloCtrl = new JFrame();
        messaggi.setBounds(20,screenSize.height/10*6+20,(int)(screenSize.width-40), screenSize.height/10*3);
        messaggi.setVisible(true);
        pannelloCtrl.setBounds(40+(int)(screenSize.width/10*7.5),20,(int)(screenSize.width/10*2)+10, screenSize.height/10*6);
        pannelloCtrl.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deserto");
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agostiniCamposampiero/deserto/resources/sand.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1030, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
    private JFrame pannelloCtrl;
    private JFrame messaggi;
    
    

}
