package agostiniCamposampiero.deserto.grafica;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import agostiniCamposampiero.deserto.deserto.Deserto;

/**
 *
 * @author giaco
 */
public class Start extends javax.swing.JFrame implements ChangeListener {
    
    private int difficulty;
    
    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        difficultySlider = new javax.swing.JSlider();
        subTitle2Start = new javax.swing.JLabel();
        titleStart = new javax.swing.JLabel();
        difficultyLabel1 = new javax.swing.JLabel();
        difficultyLabel2 = new javax.swing.JLabel();
        difficultyLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        titleStart2 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operazione Deserto");
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 245));
        getContentPane().setLayout(null);

        difficultySlider.setBackground(new java.awt.Color(255, 0, 0));
        difficultySlider.setMajorTickSpacing(1);
        difficultySlider.setMaximum(2);
        difficultySlider.setMinorTickSpacing(1);
        difficultySlider.setValue(1);
        difficultySlider.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        difficultySlider.setOpaque(false);
        difficultySlider.addChangeListener(this);
        getContentPane().add(difficultySlider);
        difficultySlider.setBounds(50, 140, 200, 26);

        subTitle2Start.setText("Difficoltà della partita");
        getContentPane().add(subTitle2Start);
        subTitle2Start.setBounds(100, 120, 140, 14);

        titleStart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleStart.setText("Simulatore di battaglia");
        getContentPane().add(titleStart);
        titleStart.setBounds(40, 20, 240, 28);

        difficultyLabel1.setText("Facile");
        getContentPane().add(difficultyLabel1);
        difficultyLabel1.setBounds(40, 170, 50, 14);

        difficultyLabel2.setText("Normale");
        getContentPane().add(difficultyLabel2);
        difficultyLabel2.setBounds(130, 170, 50, 14);

        difficultyLabel3.setText("Difficile");
        getContentPane().add(difficultyLabel3);
        difficultyLabel3.setBounds(220, 170, 50, 14);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 285, 4);

        titleStart2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleStart2.setText("Deserto");
        getContentPane().add(titleStart2);
        titleStart2.setBounds(90, 50, 120, 30);

        startButton.setLabel("Start");
        startButton.setOpaque(false);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startButton);
        startButton.setBounds(100, 210, 90, 23);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agostiniCamposampiero/deserto/resources/sand.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 300, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        Deserto.setDifficulty(difficulty);
        this.dispose();
    }//GEN-LAST:event_startButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel difficultyLabel1;
    private javax.swing.JLabel difficultyLabel2;
    private javax.swing.JLabel difficultyLabel3;
    private javax.swing.JSlider difficultySlider;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel subTitle2Start;
    private javax.swing.JLabel titleStart;
    private javax.swing.JLabel titleStart2;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Metodo invocato per modificare la difficoltà dallo slider
     * @param e     evento
     */
    @Override
    public void stateChanged(ChangeEvent e) {
        javax.swing.JSlider source = (javax.swing.JSlider)e.getSource();
        if (!source.getValueIsAdjusting()) difficulty = (int)source.getValue();
    }//stateChanged
    
}//Start
