/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agostiniCamposampiero.deserto.grafica;

/**
 *
 * @author giaco
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subTitle1Start = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSlider1 = new javax.swing.JSlider();
        subTitle2Start = new javax.swing.JLabel();
        titleStart = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        subTitle1Start.setText("Nickname giocatore");
        getContentPane().add(subTitle1Start);
        subTitle1Start.setBounds(94, 45, 130, 23);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(47, 79, 200, 20);

        jSlider1.setBackground(new java.awt.Color(255, 0, 0));
        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(2);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setOpaque(false);
        getContentPane().add(jSlider1);
        jSlider1.setBounds(47, 137, 200, 26);

        subTitle2Start.setText("Difficoltà della partita");
        getContentPane().add(subTitle2Start);
        subTitle2Start.setBounds(94, 117, 140, 14);

        titleStart.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        titleStart.setText("Deserto");
        getContentPane().add(titleStart);
        titleStart.setBounds(100, 10, 90, 29);

        jLabel4.setText("Facile");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 50, 14);

        jLabel5.setText("Normale");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(115, 169, 50, 14);

        jLabel6.setText("Difficile");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(203, 169, 50, 14);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 285, 4);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agostiniCamposampiero/deserto/resources/sand.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 290, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel subTitle1Start;
    private javax.swing.JLabel subTitle2Start;
    private javax.swing.JLabel titleStart;
    // End of variables declaration//GEN-END:variables
}
